//
//  BeerDetailPresenter.swift
//  Snoopy Beer
//
//  Created by Frederick Dupray on 08/06/2020.
//  Copyright (c) 2020 SnoopyBeer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailPresentationLogic {
    func presentBeer(response: BeerDetail.FetchBeerDetail.Response)
}

class BeerDetailPresenter: BeerDetailPresentationLogic {
    
    weak var viewController: BeerDetailDisplayLogic?
    
    func presentBeer(response: BeerDetail.FetchBeerDetail.Response) {
        let viewModel = BeerDetail.FetchBeerDetail.ViewModel(beerModel: response.beerModel)
        viewController?.displayBeer(viewModel: viewModel)
    }
}
