//
//  BeerDetailRouter.swift
//  Snoopy Beer
//
//  Created by Frederick Dupray on 08/06/2020.
//  Copyright (c) 2020 SnoopyBeer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BeerDetailRoutingLogic
{

}

protocol BeerDetailDataPassing
{
  var dataStore: BeerDetailDataStore? { get }
}

class BeerDetailRouter: NSObject, BeerDetailRoutingLogic, BeerDetailDataPassing
{
  weak var viewController: BeerDetailViewController?
  var dataStore: BeerDetailDataStore?

    
}
