//
//  BeerRouter.swift
//  Snoopy Beer
//
//  Created by Frederick Dupray on 08/06/2020.
//  Copyright (c) 2020 SnoopyBeer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerRoutingLogic {
    func routeToBeerDetail()
}

protocol BeerDataPassing {
    var dataStore: BeerDataStore? { get }
}

class BeerRouter: NSObject, BeerRoutingLogic, BeerDataPassing {
    
    weak var viewController: BeerViewController?
    var dataStore: BeerDataStore?
    
    //Instantiate and navigate
    func routeToBeerDetail() {
        let storyboard = UIStoryboard(name: "BeerDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "BeerDetailViewController") as! BeerDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToBeerDetail(source: dataStore!, destination: &destinationDS)
        navigateToBeerDetail(source: viewController, destination: destinationVC)
    }
    
    //Push VC
    func navigateToBeerDetail(source: BeerViewController?, destination: BeerDetailViewController) {
        source?.navigationController?.pushViewController(destination, animated: true)
    }
        
    //Pass data from one data store to another
    func passDataToBeerDetail(source: BeerDataStore, destination: inout BeerDetailDataStore) {
        guard let selectedBeer = source.selectedBeer?.beer else {
            return
        }
        destination.beer = BeerDetail.BeerModel(name: selectedBeer.name, descrption: selectedBeer.description, ingredients: selectedBeer.ingredients.description, food_pairings: selectedBeer.food_pairing.joined(separator: ", "), imageURL: URL(string: selectedBeer.image_url))
    }
}
